// The questions that ship uncalibrated, by skill, so `status` can list one
// that has not logged a case yet. Names only: everything else comes from the
// case records. A test checks this against each skill's own UNCALIBRATED set.

export const CATALOG = [
  'do-shit/plan_needs_human_review',
  'do-shit/fix_stays_within_item_scope',
  'changelog/id_is_this_prs_own_ticket',
  'changelog/changes_live_behaviour_without_opt_in',
  'changelog/area',
  'quick-ask-me/repo_can_answer_this',
  'quick-ask-me/answer_changes_what_gets_built',
  'quick-ask-me/criterion_is_observable',
  'quick-ask-me/scope_boundary_named',
  'quick-ask-me/seam_is_known',
  'ask-and-create-specs/matters',
  'ask-and-create-specs/user_call',
  'ask-and-create-specs/risky',
  'ask-and-create-specs/gate',
  'ask-and-create-specs/open_fork',
  'ask-and-create-specs/sliced',
  'ask-and-create-specs/section',
  'ask-and-create-specs/useful',
  'ask-and-create-specs/duplicate',
  'ask-and-create-specs/checkable',
  'wtf/same_issue_as_prior',
  'wtf/ask_not_breakage',
  'wtf/screen_was_enough',
  'review-prs/needs_lens',
  'review-prs/finding_is_actionable',
  'review-prs/same_finding',
  'review-prs/outside_stated_scope',
  'qa-this/needs_browser_check',
  'qa-this/needs_data_check',
  'qa-this/needs_new_tests',
  'qa-this/check_covers_criterion',
  'qa-this/failure_is_environmental',
  'check-infra-and-migrations/destroys_data',
  'check-infra-and-migrations/breaks_running_code',
  'check-infra-and-migrations/infra_change_is_disruptive',
  'check-infra-and-migrations/needs_manual_step',
  'check-infra-and-migrations/safe_to_push',
  'promote/branch_deploys_env',
  'promote/env_promotes_from',
  'promote/env_is_production',
  'improve-design/move_worth_doing',
  'improve-design/changes_visual_identity',
  'improve-design/direction_change_warranted',
  'improve-design/alternative_fits_better',
  'improve-design/is_improvement',
  'improve-design/harms_another_state',
];
